

-- INSERIR DADOS DE PRODUTO
DECLARE
  V_ID_CATEGORIA_PRODUTO NUMBER;
  V_ID_TIPO_PRODUTO NUMBER;  
  V_NM_PRODUTO VARCHAR2(200);
  V_DS_PRODUTO VARCHAR2(200);
  V_NM_USUARIO_ULTIMA_ALTERACAO NVARCHAR2(200);
  V_DT_ULTIMA_ALTERACAO TIMESTAMP;
    
BEGIN
---###########################
    V_ID_CATEGORIA_PRODUTO := 1;
    V_ID_TIPO_PRODUTO := 1;    
    V_NM_PRODUTO :=  'Lubrax Mineral Essencial';
    V_DS_PRODUTO := 'Lubrificante mineral que oferece ao seu veículo melhor desempenho, pois promove a redução da formação de depósitos e o controle da temperatura de operação';
    V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
    V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 14:10:10', 'DD-MM-RR HH24:MI:SS');

    PKG_HIGHFIVE.sp_ins_tbl_produto (  V_ID_CATEGORIA_PRODUTO => V_ID_CATEGORIA_PRODUTO,
        V_ID_TIPO_PRODUTO => V_ID_TIPO_PRODUTO,        
        V_NM_PRODUTO => V_NM_PRODUTO,
        V_DS_PRODUTO => V_DS_PRODUTO,
        V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
        V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
 
 ---###########################
    V_ID_CATEGORIA_PRODUTO := 1;
    V_ID_TIPO_PRODUTO := 1;    
    V_NM_PRODUTO :=  'Lubrax Mineral Plus';
    V_DS_PRODUTO := 'Lubrificante mineral que oferece ao seu veículo melhor desempenho, pois promove a redução da formação de depósitos e o controle da temperatura de operação';
    V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
    V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 14:11:10', 'DD-MM-RR HH24:MI:SS');

    PKG_HIGHFIVE.sp_ins_tbl_produto (  V_ID_CATEGORIA_PRODUTO => V_ID_CATEGORIA_PRODUTO,
        V_ID_TIPO_PRODUTO => V_ID_TIPO_PRODUTO,        
        V_NM_PRODUTO => V_NM_PRODUTO,
        V_DS_PRODUTO => V_DS_PRODUTO,
        V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
        V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
 
 ---###########################       
    V_ID_CATEGORIA_PRODUTO := 1;
    V_ID_TIPO_PRODUTO := 1;    
    V_NM_PRODUTO :=  'Castrol GTX';
    V_DS_PRODUTO := 'Lubrificante especialmente desenvolvido para utilização em motores a gasolina, álcool, GNV ou bicombustível, convencionais e turbinados';
    V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
    V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 14:20:00', 'DD-MM-RR HH24:MI:SS');
    
    PKG_HIGHFIVE.sp_ins_tbl_produto (  V_ID_CATEGORIA_PRODUTO => V_ID_CATEGORIA_PRODUTO,
        V_ID_TIPO_PRODUTO => V_ID_TIPO_PRODUTO,        
        V_NM_PRODUTO => V_NM_PRODUTO,
        V_DS_PRODUTO => V_DS_PRODUTO,
        V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
        V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
    
    
 ---###########################       
    V_ID_CATEGORIA_PRODUTO := 1;
    V_ID_TIPO_PRODUTO := 1;    
    V_NM_PRODUTO :=  'Castrol GTX Master';
    V_DS_PRODUTO := 'Lubrificante especialmente desenvolvido para utilização em motores a gasolina, álcool, GNV ou bicombustível, convencionais e turbinados';
    V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
    V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 14:21:00', 'DD-MM-RR HH24:MI:SS');
    
    PKG_HIGHFIVE.sp_ins_tbl_produto (  V_ID_CATEGORIA_PRODUTO => V_ID_CATEGORIA_PRODUTO,
        V_ID_TIPO_PRODUTO => V_ID_TIPO_PRODUTO,        
        V_NM_PRODUTO => V_NM_PRODUTO,
        V_DS_PRODUTO => V_DS_PRODUTO,
        V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
        V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ; 
        
  ---###########################      
  V_ID_CATEGORIA_PRODUTO := 1;
    V_ID_TIPO_PRODUTO := 2;    
    V_NM_PRODUTO :=  'Shell Helix Alta Quilometragem';
    V_DS_PRODUTO := 'Proteção extra para motores com alta quilometragem';
    V_NM_USUARIO_ULTIMA_ALTERACAO := 'ana.souza';
    V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 14:21:00', 'DD-MM-RR HH24:MI:SS');
    
    PKG_HIGHFIVE.sp_ins_tbl_produto (  V_ID_CATEGORIA_PRODUTO => V_ID_CATEGORIA_PRODUTO,
        V_ID_TIPO_PRODUTO => V_ID_TIPO_PRODUTO,        
        V_NM_PRODUTO => V_NM_PRODUTO,
        V_DS_PRODUTO => V_DS_PRODUTO,
        V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
        V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  

  
  ---###########################      
  V_ID_CATEGORIA_PRODUTO := 1;
    V_ID_TIPO_PRODUTO := 2;    
    V_NM_PRODUTO :=  'Shell Helix Turbo';
    V_DS_PRODUTO := 'Proteção extra para motores com alta quilometragem';
    V_NM_USUARIO_ULTIMA_ALTERACAO := 'ana.souza';
    V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 14:51:00', 'DD-MM-RR HH24:MI:SS');
    
    PKG_HIGHFIVE.sp_ins_tbl_produto (  V_ID_CATEGORIA_PRODUTO => V_ID_CATEGORIA_PRODUTO,
        V_ID_TIPO_PRODUTO => V_ID_TIPO_PRODUTO,        
        V_NM_PRODUTO => V_NM_PRODUTO,
        V_DS_PRODUTO => V_DS_PRODUTO,
        V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
        V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  

        
END;

SELECT * FROM tbl_produto;
SELECT * FROM  tbl_log_produto;


-- INSERIR VINCULO DE PRODUTO E GRADUCAO
DECLARE
  V_ID_GRADUACAO NUMBER;
  V_ID_PRODUTO NUMBER;
  V_NM_USUARIO_ULTIMA_ALTERACAO NVARCHAR2(200);
  V_DT_ULTIMA_ALTERACAO TIMESTAMP;
    
BEGIN
--##################
  V_ID_GRADUACAO := 1;
  V_ID_PRODUTO := 1;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:51:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_graduacao_produto (  V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_ID_PRODUTO => V_ID_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  

--##################
  V_ID_GRADUACAO := 3;
  V_ID_PRODUTO := 1;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:53:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_graduacao_produto (  V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_ID_PRODUTO => V_ID_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  


--##################
  V_ID_GRADUACAO := 2;
  V_ID_PRODUTO := 2;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:54:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_graduacao_produto (  V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_ID_PRODUTO => V_ID_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  


--##################
  V_ID_GRADUACAO := 4;
  V_ID_PRODUTO := 3;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ricardo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:56:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_graduacao_produto (  V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_ID_PRODUTO => V_ID_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  


--##################
  V_ID_GRADUACAO := 2;
  V_ID_PRODUTO := 5;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ricardo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:57:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_graduacao_produto (  V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_ID_PRODUTO => V_ID_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  

END;


SELECT * FROM tbl_graduacao_produto;
SELECT * FROM tbl_log_graduacao_produto;



--  INSERIR VINCULO DE PRODUTO E PRECO
DECLARE
  V_ID_PRODUTO NUMBER;
  V_ID_GRADUACAO NUMBER;
  V_VL_QUANTIDADE NUMBER;
  V_VL_PRODUTO NUMBER;
  V_NM_USUARIO_ULTIMA_ALTERACAO NVARCHAR2(200);
  V_DT_ULTIMA_ALTERACAO TIMESTAMP;
    
BEGIN
--############################
  V_ID_PRODUTO := 3;
  V_ID_GRADUACAO := 4;
  V_VL_QUANTIDADE := 500;
  V_VL_PRODUTO := 25.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ricardo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:57:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;
    
    
--############################
  V_ID_PRODUTO := 3;
  V_ID_GRADUACAO := 4;
  V_VL_QUANTIDADE := 5000;
  V_VL_PRODUTO := 250.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ricardo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:50:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
    
--############################
  V_ID_PRODUTO := 1;
  V_ID_GRADUACAO := 1;
  V_VL_QUANTIDADE := 500;
  V_VL_PRODUTO := 21.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ricardo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:50:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
    
--############################
  V_ID_PRODUTO := 1;
  V_ID_GRADUACAO := 3;
  V_VL_QUANTIDADE := 500;
  V_VL_PRODUTO := 55.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:23:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
    
--############################
  V_ID_PRODUTO := 2;
  V_ID_GRADUACAO := 2;
  V_VL_QUANTIDADE := 500;
  V_VL_PRODUTO := 50.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ricardo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 14:56:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
    
--############################
  V_ID_PRODUTO := 5;
  V_ID_GRADUACAO := 2;
  V_VL_QUANTIDADE := 500;
  V_VL_PRODUTO := 51.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'ana.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 11:50:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  

--############################
  V_ID_PRODUTO := 5;
  V_ID_GRADUACAO := 2;
  V_VL_QUANTIDADE := 5000;
  V_VL_PRODUTO := 256.50;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'paulo.silva';
  V_DT_ULTIMA_ALTERACAO :=  TO_TIMESTAMP ('10-05-22 13:50:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_ins_tbl_preco_produto (  V_ID_PRODUTO => V_ID_PRODUTO,
    V_ID_GRADUACAO => V_ID_GRADUACAO,
    V_VL_QUANTIDADE => V_VL_QUANTIDADE,
    V_VL_PRODUTO => V_VL_PRODUTO,
    V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
    V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
END;

SELECT * FROM tbl_preco_produto
SELECT * FROM tbl_log_preco_produto



-- ALTERACAO DO PRECO DO PRODUTO
DECLARE
  V_ID_PRECO_PRODUTO NUMBER;
  V_ID_PRODUTO NUMBER;
  V_ID_GRADUACAO NUMBER;
  V_VL_QUANTIDADE NUMBER;
  V_VL_PRODUTO NUMBER;
  V_NM_USUARIO_ULTIMA_ALTERACAO NVARCHAR2(200);
  V_DT_ULTIMA_ALTERACAO TIMESTAMP;
    
BEGIN
  V_ID_PRECO_PRODUTO := 3;
  V_ID_PRODUTO := 1;
  V_ID_GRADUACAO := 1;
  V_VL_QUANTIDADE := 500;
  V_VL_PRODUTO := 30.59;
  V_NM_USUARIO_ULTIMA_ALTERACAO := 'antonio.batista';
  V_DT_ULTIMA_ALTERACAO := TO_TIMESTAMP ('10-05-22 13:50:00', 'DD-MM-RR HH24:MI:SS');

  PKG_HIGHFIVE.sp_upd_tbl_preco_produto (  V_ID_PRECO_PRODUTO => V_ID_PRECO_PRODUTO,
V_ID_PRODUTO => V_ID_PRODUTO,
V_ID_GRADUACAO => V_ID_GRADUACAO,
V_VL_QUANTIDADE => V_VL_QUANTIDADE,
V_VL_PRODUTO => V_VL_PRODUTO,
V_NM_USUARIO_ULTIMA_ALTERACAO => V_NM_USUARIO_ULTIMA_ALTERACAO,
V_DT_ULTIMA_ALTERACAO => V_DT_ULTIMA_ALTERACAO) ;  
END;

SELECT * FROM tbl_preco_produto WHERE id_produto = 1;
SELECT * FROM tbl_log_preco_produto WHERE id_produto = 1;



/*
DELETE FROM tbl_preco_produto;
DELETE FROM tbl_log_preco_produto;
COMMIT;

DELETE FROM tbl_graduacao_produto;
DELETE FROM tbl_log_graduacao_produto;
COMMIT;

DELETE FROM tbl_produto;
DELETE FROM tbl_log_produto;
COMMIT;

*/



