-- SELECT 'DROP TABLE '||TABLE_NAME||' CASCADE CONSTRAINTS;' FROM USER_TABLES;
-- SELECT 'DROP SEQUENCE '||SEQUENCE_NAME||';' FROM USER_SEQUENCES;

DROP TABLE T_HT_ALIMENTACAO CASCADE CONSTRAINTS;
DROP TABLE T_HT_CAT_ALIMENTACAO CASCADE CONSTRAINTS;
DROP TABLE T_HT_EXERCICIO CASCADE CONSTRAINTS;
DROP TABLE T_HT_PLANO CASCADE CONSTRAINTS;
DROP TABLE T_HT_PORCAO CASCADE CONSTRAINTS;
DROP TABLE T_HT_USR_ALIMENTACAO CASCADE CONSTRAINTS;
DROP TABLE T_HT_USR_EXERCICIO CASCADE CONSTRAINTS;
DROP TABLE T_HT_USR_PLANO CASCADE CONSTRAINTS;
DROP TABLE T_HT_USUARIO CASCADE CONSTRAINTS;